### ISSUE TITLE
Mobile app?

### ISSUE THREAD

**Issue by Bucko-m** [fragaria/karmen-octoprint-plugin#1]
Hello,

I really like this, I wondered if there are any plans for a mobile app? I'm android and I could help test. It be nice to check on my printer in the app while I'm on the go instead of checking in the browser.

Thanks :).

**Comment by voyczech** [comment]
Hi @Bucko-m 
we doesn't have plan to create separate app.
Web interface is possible to turn into PWA (A progressive web application) instruction depends on system of your phone.
Thanks for understanding.

Best regards
voyczech
