### ISSUE TITLE
Camera not working

### ISSUE THREAD

**Issue by swheettaos** [fragaria/karmen-octoprint-plugin#2]
I have multiple cameras, and I'm using the multicam plugin.  It works from the octoprint web interface, it also works from octoeverywhere plugin (and then octopod iPhone app).  Karmen website never displays the camera and doesn't seem to let me see either camera.  

It lets me connect to the printer from Karmen and upload gcode files .. but the cameras don't work.

Also, when upload my gcode from Prusa, I then need to manually login to the Karmen site to select the gcode file I want to print.  I'd love a way to upload from Prusa and by which api key I use to connect to karmen with, auto-select a printer and have it sent automatically. This would be nice to have.

I have one BIG issue which is a blocker for me.  I need to be able to upload from Karmen but **not** print to octoprint.  I have pre-print plugins that process the gcode (like arc-welder).  Once pre-print processing has been completed, I have it set to auto-start the print.  When I upload from the Karmen site it kicked off the print job before my pre-print processes can be completed.  Making this unusable.  Currently, I use the upload-only option from Prusa directly to octoprint and it works as desired. 

This is a great product and I know it's free so I'm willing to contribute if I can use it.  I contribute to OctoPrint and a couple of other plugin developers currently.  Thanks for all the hard work on this, it's awesome.

**Comment by voyczech** [comment]
Hi @swheettaos,
sorry for late reply.
Did I understand correctly that you use moltiple camera for one printer?
Karmen work with one stream per printer but I will asked our devs if it will possible to get this feature.

Thanks for mention pre-print plugins I will put it into backlogs to have focus on that.
Currently couldn't promise some date and priority on pipeline.

If you have another request or recommendation for new feature feel free to write it to our forum into this thread.
Forum is for all karmen users.
[https://forum.karmen.tech/c/feature-requests-and-ideas/6](https://forum.karmen.tech/c/feature-requests-and-ideas/6
)
Thanks for your feedback and sorry for late reply.
Have a nice day.
